all:
	g++ -o tomCurve Tom_curve.cpp -lglut -lGL -lGLU -lglui ../PixelLab/lib/libpixelLab_linux.a ../PixelLab/lib/libpng12_linux64.a -lz

	g++ -o spaceFilterII Space_filter_II.cpp -lglut -lGL -lGLU -lglui ../PixelLab/lib/libpixelLab_linux.a ../PixelLab/lib/libpng12_linux64.a -lz

	g++ -o frequencyFilters Frequency_Filters.cpp -lglut -lGL -lGLU -lglui ../PixelLab/lib/libpixelLab_linux.a ../PixelLab/lib/libpng12_linux64.a -lz

	g++ -o frequencyFiltersSalPimenta Frequency_Filters_SalPimenta.cpp -lglut -lGL -lGLU -lglui ../PixelLab/lib/libpixelLab_linux.a ../PixelLab/lib/libpng12_linux64.a -lz

	g++ -o imageSegmentation Image_Segmentation.cpp -lglut -lGL -lGLU -lglui ../PixelLab/lib/libpixelLab_linux.a ../PixelLab/lib/libpng12_linux64.a -lz

	g++ -o morphologicalProcessing Morphological_Processing.cpp -lglut -lGL -lGLU -lglui ../PixelLab/lib/libpixelLab_linux.a ../PixelLab/lib/libpng12_linux64.a -lz

	g++ -o morphologicalProcessing2 Morphological_Processing_2.cpp -lglut -lGL -lGLU -lglui ../PixelLab/lib/libpixelLab_linux.a ../PixelLab/lib/libpng12_linux64.a -lz

	g++ -o consolidation Consolidation.cpp -lglut -lGL -lGLU -lglui ../PixelLab/lib/libpixelLab_linux.a ../PixelLab/lib/libpng12_linux64.a -lz
	./consolidation
